# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
# - markdown: kramdown

title: "Phil Stollery"
tagline: ""
description: "Follow <a href=\"https://micro.blog/philstollery\">@philstollery on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/philstollery\">@philstollery on Micro.blog</a>."
baseurl: ""
url: "https://www.stollerys.co.uk"
markdown: "kramdown"
username: "philstollery"
microblog_user: "philstollery"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Phil Stollery"
name: "Phil Stollery"
gravatar_hash: "39d51f68845d7a838c1293d6862fd91c"
avatar: "https://micro.blog/philstollery/avatar.jpg"
full_name: "Phil Stollery"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "WET"
site_id: "3017"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"